### PR TITLE
Refine CSVHub

### PR DESCRIPTION
**Pull request by wy-z**
- Update selector
- Format code with prettier
- Update manifest 'matches' to support GitHub Enterprise
- Work only in 'unified' mode

### CODE REVIEW

**Comment by wy-z** [comment]
image

**Comment by wy-z** [comment]
@Floppy Hi~
Could you please review my PR?

**Comment by Floppy** [comment]
Hi @wy-z, I didn't have access to this repo, but have now taken it over again, so I can! Thanks for sending it in, I'll take a look as soon as I can.

**Comment by Floppy** [comment]
Wow, turns out this completely slipped my mind. Sorry.

**Pull request merged**
